# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniTwitterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiniTwitterApp
pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'KeychainSwift'
  pod 'SVProgressHUD'
  pod 'Simple-Networking', '~> 0.3.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'FirebaseCrashlytics'

  target 'MiniTwitterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiniTwitterAppUITests' do
    # Pods for testing
  end

end
